name: "CI"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Update NPM
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Boostrap Lerna packages
        run: npm run bootstrap

      - name: Run all tests
        run: npm run test:ci

      - name: Build all packages
        run: npm run build

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          working-directory: ./packages/server

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/docs/build
          cname: template.viotech.io
